sudo: required
dist: trusty
language: python

cache:
  - pip
  - apt

python:
  - 2.7
  - 3.6

install:
  - pip install -r dev_requirements.txt

script:
  - python setup.py test
  - python setup.py sdist bdist bdist_wheel

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  password:
    secure: FH/uQUSHE/5/ahHddlriVLsEA0IBwt9AnIMGoCMEVOBXUM6cElNQSwykmvvO60JnOYgMFM/0UJRlsRStw5Q9ocRk8vaj9OK+rYJYokRX/+W0YP5NCB/GGtedHz7MQ+HQrZQoeJ/HUcth1a3XLgElAJh47rL8RyA44a/pyF+4KLCgBwhnajjE+kEJ9S5r5vyLKVvdj6b5SqbYSQq65ww4rtXgA0i2QNFpTK0mfkRvi40O1AFXqSB6E37xTd8rtQdehL/RJk4f6vlPQai/WHd2MJirUXXMVHsev7QS33pygqEaOEaaa/EG6Te4pDxw6M+qlSUNreO/8iAlx/b8bWRxGclMeMfI+HgtdrlvcqUa9bzLZoWnJv6MDX70G1ZV/1nIVrLetLbxOT7neYzp6lYx+8CCQ4N/jui4sSrur2C5hnwvpz0ug7dBCMQM1rrvXUAYX/iKDF5aA2TPfHTQVaErxBtYfS06hYWZmYtqb9t4rCGh3qjjXMnc5FVZEGahuzBdHOnxYAcIJBdhWGuPKr53C7HOZdM+UlV71TFGWDSC3HWuIDeYyfjd7uDxUCPRzUr/4m2WAifc5HBh16eWtRoroEqma3uiutoPsoU/0nUO8LinFLfFQ9UACU4nPt5sh3GShCLslRt0epW1xhXGA1Tg2vmyRf2BaLVJgsdYuE0O7MY=
